# Generated by Django 5.2 on 2025-04-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
