# Generated by Django 5.2 on 2025-04-14 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='SalaJuntas',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('equipo', models.TextField()),
                ('capacidad', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'salas_de_juntas',
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=200)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.area')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empleado')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salajuntas')),
            ],
            options={
                'db_table': 'reservaciones',
            },
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitados', to='api.reservacion')),
            ],
            options={
                'db_table': 'invitados',
            },
        ),
    ]
