# Generated by Django 5.2 on 2025-04-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_area_salajuntas_reservacion_invitado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='area',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='invitado',
            name='reservacion',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='sala',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Invitado',
        ),
        migrations.DeleteModel(
            name='Reservacion',
        ),
        migrations.DeleteModel(
            name='SalaJuntas',
        ),
    ]
