# Generated by Django 5.2 on 2025-04-14 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_reservacion_area_remove_empleado_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID de Área (abreviatura)')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id_invitado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'invitados',
            },
        ),
        migrations.CreateModel(
            name='SalaJuntas',
            fields=[
                ('id_sala', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID de Sala (abreviatura)')),
                ('nombre', models.CharField(max_length=100)),
                ('equipo', models.TextField()),
                ('capacidad', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'salas_juntas',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('empleado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('numero_empleado', models.CharField(max_length=20, unique=True)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=200)),
                ('comentarios', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.area')),
                ('invitados', models.ManyToManyField(blank=True, to='api.invitado')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salajuntas')),
            ],
            options={
                'db_table': 'reservaciones',
            },
        ),
    ]
