# Generated by Django 5.2 on 2025-04-14 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_area_invitado_salajuntas_empleado_reservacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='correo_electronico',
        ),
    ]
