# Generated by Django 5.2 on 2025-04-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_empleado_correo_electronico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='area',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='invitados',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='sala',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Invitado',
        ),
        migrations.DeleteModel(
            name='Reservacion',
        ),
        migrations.DeleteModel(
            name='SalaJuntas',
        ),
    ]
