# Generated by Django 5.2 on 2025-04-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_reservacion_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaJuntasTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sala_temporal', models.IntegerField()),
            ],
        ),
    ]
