# Generated by Django 5.2 on 2025-04-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_salajuntas_id_sala'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalaJuntasTemporal',
        ),
    ]
