# Generated by Django 5.2 on 2025-05-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_reservacion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='enviar_correo',
            field=models.BooleanField(default=False),
        ),
    ]
