# Generated by Django 5.2 on 2025-06-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_reservacion_invitados_alter_invitado_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='detectar_personas',
            field=models.BooleanField(default=True),
        ),
    ]
