# Generated by Django 5.2 on 2025-06-04 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_reservacion_detectar_personas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeteccionPersona',
            fields=[
                ('id_deteccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('numero_personas', models.IntegerField()),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reservacion')),
            ],
            options={
                'verbose_name': 'Detección de Persona',
                'verbose_name_plural': 'Detecciones de Personas',
            },
        ),
    ]
