# Generated by Django 5.2 on 2025-06-04 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_deteccionpersona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='detectar_personas',
        ),
        migrations.AddField(
            model_name='reservacion',
            name='monitorear',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='FotoReservacion',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='fotos_reservaciones/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='api.reservacion')),
            ],
            options={
                'db_table': 'fotos_reservaciones',
            },
        ),
        migrations.DeleteModel(
            name='DeteccionPersona',
        ),
    ]
