# Generated by Django 5.2 on 2025-07-14 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_reservacion_monitorear_delete_fotoreservacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='monitorear',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ConteoPersonas',
            fields=[
                ('id_conteo', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='conteos/')),
                ('personas_contadas', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reservacion')),
            ],
            options={
                'db_table': 'conteos_personas',
            },
        ),
    ]
